import { Geist, Geist_Mono, Oswald, Inter } from "next/font/google";
import "./globals.css";

import Footer from "../Components/Footer";
import Navbar from "../Components/Navbar/Navbar";
import FitlogProvider from "../Context/FitlogContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter-custom",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fit Log App",
  description: "Generated by Fit Log App",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <FitlogProvider>
          <Navbar />
          {children}
          <Footer />
          <ToastContainer />
        </FitlogProvider>
      </body>
    </html>
  );
}